apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: app
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: redis
          image: redis:7.0
          ports:
            - containerPort: 6379
          # Enable durable persistence (AOF)
          args: ["--appendonly", "yes", "--appendfsync", "everysec"]
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
        # Use a StorageClass that exists in your cluster:
        #   kubectl get storageclass
        storageClassName: standard-rwo
