apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-storage
  namespace: app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
