apiVersion: v1
kind: Service
metadata:
  name: devops-assistant
  namespace: app
  annotations:
   # For GKE < 1.16.8-gke.3 use "beta.cloud.google.com/backend-config" below 
   cloud.google.com/backend-config: '{"default": "my-bsc-backendconfig"}'
spec:
  selector:
    app: ollama
  ports:
  - protocol: TCP
    port: 11434
    targetPort: 11434
  type: ClusterIP
