apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ensemble-pvc
  namespace: app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
