apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: prometheus
stringData:
  pushgateway.yaml: |
    - job_name: 'pushgateway'
      honor_labels: true
      metrics_path: /metrics
      static_configs:
        - targets:
            - 'pushgateway-prometheus-pushgateway.prometheus.svc.cluster.local:9091'
