apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-scrape-configs
  namespace: prometheus
data:
  pushgateway.yaml: |
    - job_name: 'pushgateway'
      honor_labels: true
      static_configs:
        - targets:
            - 'pushgateway-prometheus-pushgateway.prometheus.svc.cluster.local:9091'
