apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: app
type: Opaque
data:
  # base64 encoded: echo -n "yourpassword" | base64
  mysql-root-password: TWFuemFANDI0Mg==  # "password"