apiVersion: batch/v1
kind: CronJob
metadata:
  name: combined-stress
  namespace: app
spec:
  schedule: "00 21 * * *"   # 9:00 PM daily
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: k6
            image: grafana/k6:latest
            command: ["k6", "run", "/scripts/anomaly.js"]
            volumeMounts:
              - name: script-volume
                mountPath: /scripts

          - name: stress-ng
            image: alexeiled/stress-ng:latest
            command:
              - /usr/bin/stress-ng
            args:
              - "--cpu"
              - "1"
              - "--vm"
              - "1"
              - "--vm-bytes"
              - "300M"
              - "--timeout"
              - "90s"

          volumes:
            - name: script-volume
              configMap:
                name: k6-scripts-combined

          restartPolicy: OnFailure
