apiVersion: batch/v1
kind: CronJob
metadata:
  name: normal-load
  namespace: app
spec:
  schedule: "0 6,12,18 * * *"  # 6 AM, 12 PM, 6 PM UTC
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: k6
            image: grafana/k6
            command: ["k6", "run", "/scripts/normal.js"]
            volumeMounts:
              - name: script-volume
                mountPath: /scripts
          volumes:
            - name: script-volume
              configMap:
                name: k6-scripts-combined
          restartPolicy: OnFailure
