apiVersion: batch/v1
kind: CronJob
metadata:
  name: transient-service-spike
  namespace: app
spec:
  schedule: "20 12 * * *"  # runs daily at 2:00 UTC (adjust if needed)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: k6
            image: grafana/k6
            imagePullPolicy: Always
            command: ["k6", "run", "/scripts/transient-spike.js"]
            volumeMounts:
            - name: script-volume
              mountPath: /scripts
          restartPolicy: OnFailure
          volumes:
          - name: script-volume
            configMap:
              name: transient-spike-script
